<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        // Skip when schema already imported (parity / local imported databases).
        if (Schema::hasTable('sch_settings')) {
            return;
        }

        DB::unprepared('ALTER TABLE `addons` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `addon_versions` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `alumni_events` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `alumni_students` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `annual_calendar` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `api_session` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `attendence_type` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `books` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `book_issues` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `captcha` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `categories` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `certificates` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `chat_connections` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `chat_messages` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `chat_users` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `classes` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `class_sections` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `class_section_times` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `class_teacher` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `complaint` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `complaint_type` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `contents` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `content_for` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `content_types` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `cumulative_fine` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `currencies` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `custom_fields` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `custom_field_values` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `daily_assignment` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `department` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `disable_reason` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `dispatch_receive` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `email_attachments` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `email_config` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `email_template` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `email_template_attachment` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `enquiry` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `enquiry_type` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `events` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `exams` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `exam_groups` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `exam_group_class_batch_exams` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `exam_group_class_batch_exam_students` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `exam_group_class_batch_exam_subjects` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `exam_group_exam_connections` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `exam_group_exam_results` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `exam_group_students` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `exam_schedules` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `expenses` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `expense_head` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `feemasters` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `fees_discounts` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `fees_reminder` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `feetype` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `fee_groups` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `fee_groups_feetype` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `fee_receipt_no` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `fee_session_groups` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `filetypes` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `follow_up` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `front_cms_media_gallery` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `front_cms_menus` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `front_cms_menu_items` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `front_cms_pages` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `front_cms_page_contents` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `front_cms_programs` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `front_cms_program_photos` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `front_cms_settings` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `gateway_ins` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `gateway_ins_response` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `general_calls` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `google_drive_setting` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `grades` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `holiday_type` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `homework` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `homework_evaluation` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `hostel` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `hostel_rooms` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `id_card` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `income` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `income_head` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `item` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `item_category` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `item_issue` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `item_stock` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `item_store` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `item_supplier` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `languages` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `leave_types` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `lesson` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `lesson_plan_forum` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `libarary_members` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `logs` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `mark_divisions` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `messages` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `notification_roles` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `notification_setting` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `offline_fees_payments` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `onlineexam` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `onlineexam_attempts` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `onlineexam_questions` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `onlineexam_students` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `onlineexam_student_results` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `online_admissions` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `online_admission_custom_field_value` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `online_admission_fields` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `online_admission_payment` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `payment_settings` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `payslip_allowance` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `permission_category` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `permission_group` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `permission_student` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `pickup_point` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `print_headerfooter` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `questions` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `read_notification` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `reference` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `resume_additional_fields_settings` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `resume_settings_fields` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `roles` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `roles_permissions` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `room_types` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `route_pickup_point` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `school_houses` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `sch_settings` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `sections` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `send_notification` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `sessions` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `share_contents` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `share_content_for` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `share_upload_contents` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `sidebar_menus` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `sidebar_sub_menus` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `sms_config` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `sms_template` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `source` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `staff` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `staff_attendance` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `staff_attendance_type` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `staff_attendence_schedules` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `staff_designation` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `staff_id_card` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `staff_leave_details` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `staff_leave_request` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `staff_payroll` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `staff_payslip` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `staff_rating` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `staff_roles` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `staff_timeline` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `students` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `student_applied_discounts` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `student_applyleave` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `student_attendences` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `student_attendence_schedules` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `student_dashboard_settings` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `student_doc` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `student_edit_fields` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `student_educational_details` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `student_fees` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `student_fees_deposite` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `student_fees_discounts` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `student_fees_master` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `student_fees_processing` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `student_refrence` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `student_session` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `student_skills_detail` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `student_subject_attendances` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `student_timeline` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `student_transport_fees` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `student_work_experience` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `subjects` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `subject_groups` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `subject_group_class_sections` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `subject_group_subjects` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `subject_syllabus` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `subject_timetable` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `submit_assignment` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `template_admitcards` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `template_marksheets` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `topic` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `transfer_certificate_fields` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `transfer_certificate_no` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `transfer_certificate_settings` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `transport_feemaster` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `transport_route` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `upload_contents` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `userlog` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `users` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `users_authentication` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `vehicles` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `vehicle_routes` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `video_tutorial` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `video_tutorial_class_sections` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `visitors_book` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `visitors_purpose` ADD PRIMARY KEY (`id`)');
        DB::unprepared('ALTER TABLE `addons` MODIFY `id`int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11');
        DB::unprepared('ALTER TABLE `addon_versions` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `alumni_events` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `alumni_students` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `annual_calendar` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `api_session` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `attendence_type` MODIFY `id`int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7');
        DB::unprepared('ALTER TABLE `books` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `book_issues` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `captcha` MODIFY `id`int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6');
        DB::unprepared('ALTER TABLE `categories` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `certificates` MODIFY `id`int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2');
        DB::unprepared('ALTER TABLE `chat_connections` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `chat_messages` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `chat_users` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `classes` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `class_sections` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `class_section_times` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `class_teacher` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `complaint` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `complaint_type` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `contents` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `content_for` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `content_types` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `cumulative_fine` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `currencies` MODIFY `id`int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=180');
        DB::unprepared('ALTER TABLE `custom_fields` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `custom_field_values` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `daily_assignment` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `department` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `disable_reason` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `dispatch_receive` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `email_attachments` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `email_config` MODIFY `id`int UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2');
        DB::unprepared('ALTER TABLE `email_template` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `email_template_attachment` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `enquiry` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `enquiry_type` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `events` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `exams` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `exam_groups` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `exam_group_class_batch_exams` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `exam_group_class_batch_exam_students` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `exam_group_class_batch_exam_subjects` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `exam_group_exam_connections` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `exam_group_exam_results` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `exam_group_students` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `exam_schedules` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `expenses` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `expense_head` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `feemasters` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `fees_discounts` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `fees_reminder` MODIFY `id`int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5');
        DB::unprepared('ALTER TABLE `feetype` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `fee_groups` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `fee_groups_feetype` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `fee_receipt_no` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `fee_session_groups` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `filetypes` MODIFY `id`int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2');
        DB::unprepared('ALTER TABLE `follow_up` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `front_cms_media_gallery` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `front_cms_menus` MODIFY `id`int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3');
        DB::unprepared('ALTER TABLE `front_cms_menu_items` MODIFY `id`int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5');
        DB::unprepared('ALTER TABLE `front_cms_pages` MODIFY `id`int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5');
        DB::unprepared('ALTER TABLE `front_cms_page_contents` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `front_cms_programs` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `front_cms_program_photos` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `front_cms_settings` MODIFY `id`int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2');
        DB::unprepared('ALTER TABLE `gateway_ins` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `gateway_ins_response` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `general_calls` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `google_drive_setting` MODIFY `id`int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2');
        DB::unprepared('ALTER TABLE `grades` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `holiday_type` MODIFY `id`int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4');
        DB::unprepared('ALTER TABLE `homework` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `homework_evaluation` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `hostel` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `hostel_rooms` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `id_card` MODIFY `id`int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3');
        DB::unprepared('ALTER TABLE `income` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `income_head` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `item` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `item_category` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `item_issue` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `item_stock` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `item_store` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `item_supplier` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `languages` MODIFY `id`int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=95');
        DB::unprepared('ALTER TABLE `leave_types` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `lesson` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `lesson_plan_forum` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `libarary_members` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `logs` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `mark_divisions` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `messages` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `notification_roles` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `notification_setting` MODIFY `id`int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=23');
        DB::unprepared('ALTER TABLE `offline_fees_payments` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `onlineexam` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `onlineexam_attempts` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `onlineexam_questions` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `onlineexam_students` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `onlineexam_student_results` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `online_admissions` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `online_admission_custom_field_value` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `online_admission_fields` MODIFY `id`int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=42');
        DB::unprepared('ALTER TABLE `online_admission_payment` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `payment_settings` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `payslip_allowance` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `permission_category` MODIFY `id`int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=295');
        DB::unprepared('ALTER TABLE `permission_group` MODIFY `id`int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=32');
        DB::unprepared('ALTER TABLE `permission_student` MODIFY `id`int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=26');
        DB::unprepared('ALTER TABLE `pickup_point` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `print_headerfooter` MODIFY `id`int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7');
        DB::unprepared('ALTER TABLE `questions` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `read_notification` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `reference` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `resume_additional_fields_settings` MODIFY `id`int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6');
        DB::unprepared('ALTER TABLE `resume_settings_fields` MODIFY `id`int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=36');
        DB::unprepared('ALTER TABLE `roles` MODIFY `id`int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8');
        DB::unprepared('ALTER TABLE `roles_permissions` MODIFY `id`int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1487');
        DB::unprepared('ALTER TABLE `room_types` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `route_pickup_point` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `school_houses` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `sections` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `send_notification` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `sessions` MODIFY `id`int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=26');
        DB::unprepared('ALTER TABLE `share_contents` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `share_content_for` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `share_upload_contents` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `sidebar_menus` MODIFY `id`int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=38');
        DB::unprepared('ALTER TABLE `sidebar_sub_menus` MODIFY `id`int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=231');
        DB::unprepared('ALTER TABLE `sms_config` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `sms_template` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `source` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `staff` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `staff_attendance` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `staff_attendance_type` MODIFY `id`int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7');
        DB::unprepared('ALTER TABLE `staff_attendence_schedules` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `staff_designation` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `staff_id_card` MODIFY `id`int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3');
        DB::unprepared('ALTER TABLE `staff_leave_details` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `staff_leave_request` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `staff_payroll` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `staff_payslip` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `staff_rating` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `staff_roles` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `staff_timeline` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `students` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `student_applied_discounts` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `student_applyleave` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `student_attendences` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `student_attendence_schedules` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `student_dashboard_settings` MODIFY `id`int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9');
        DB::unprepared('ALTER TABLE `student_doc` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `student_edit_fields` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `student_educational_details` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `student_fees` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `student_fees_deposite` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `student_fees_discounts` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `student_fees_master` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `student_fees_processing` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `student_refrence` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `student_session` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `student_skills_detail` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `student_subject_attendances` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `student_timeline` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `student_transport_fees` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `student_work_experience` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `subjects` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `subject_groups` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `subject_group_class_sections` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `subject_group_subjects` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `subject_syllabus` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `subject_timetable` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `submit_assignment` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `template_admitcards` MODIFY `id`int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2');
        DB::unprepared('ALTER TABLE `template_marksheets` MODIFY `id`int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2');
        DB::unprepared('ALTER TABLE `topic` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `transfer_certificate_fields` MODIFY `id`int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=42');
        DB::unprepared('ALTER TABLE `transfer_certificate_no` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `transfer_certificate_settings` MODIFY `id`int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2');
        DB::unprepared('ALTER TABLE `transport_feemaster` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `transport_route` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `upload_contents` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `userlog` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `users` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `users_authentication` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `vehicles` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `vehicle_routes` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `video_tutorial` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `video_tutorial_class_sections` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `visitors_book` MODIFY `id`int NOT NULL AUTO_INCREMENT');
        DB::unprepared('ALTER TABLE `visitors_purpose` MODIFY `id`int NOT NULL AUTO_INCREMENT');

    }

    public function down(): void
    {
        // Irreversible baseline — restore from database/dumps instead.
    }
};
